name: Deploy
on:
  workflow_dispatch:

env:
  HOST: treeton.org

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ env.HOST }}
          port: 22
          username: root
          key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
          source: docker,docker-compose.yaml,.env.prod
          target: /srv/${{ github.repository }}
          overwrite: true

      - name: Docker compose up
        uses: appleboy/ssh-action@v0.1.5
        with:
          script: |
            cd /srv/${{ github.repository }}
            rm -rf .htpasswd
            touch .htpasswd
            htpasswd -bB .htpasswd ${{ secrets.BASIC_AUTH_USER }} ${{ secrets.BASIC_AUTH_PASSWORD }}
            docker compose --env-file .env.prod pull
            docker compose --env-file .env.prod down
            docker compose --env-file .env.prod up -d
          host: ${{ env.HOST }}
          port: 22
          username: root
          key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}